### ISSUE TITLE
Linker issue on Ubuntu 13.10

### ISSUE THREAD

**Issue by paoloambrosio** [cucumber/cucumber-cpp#68]
After upgrading from Ubuntu 12.10 to 13.10, I've started getting linker errors:

```
.../3rd_party/lib/libgtest.so: undefined reference to `pthread_key_create'
.../3rd_party/lib/libgtest.so: undefined reference to `pthread_getspecific'
.../3rd_party/lib/libgtest.so: undefined reference to `pthread_key_delete'
.../3rd_party/lib/libgtest.so: undefined reference to `pthread_setspecific'
```

It looks like the linker needs libraries to be defined in a specific order. This seems to be caused by the `--as-needed` option that is default in ld for the system.
