### ISSUE TITLE
Build fails with Boost 1.66.0

### ISSUE THREAD

**Issue by fxcoudert** [cucumber/cucumber-cpp#178]
On macOS (all supported versions), we found out while testing Boost 1.66.0 for Homebrew that cucumber-cpp 0.4 fails to build with Boost 1.66.0, giving the following errors:

```
In file included from /tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:1:
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/include/cucumber-cpp/internal/connectors/wire/WireServer.hpp:39:19: error: too many template arguments for class template 'basic_socket_acceptor'
    void doListen(basic_socket_acceptor<Protocol, Service>& acceptor,
                  ^                               ~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
In file included from /tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:1:
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/include/cucumber-cpp/internal/connectors/wire/WireServer.hpp:42:23: error: too many template arguments for class template 'basic_socket_acceptor'
    void doAcceptOnce(basic_socket_acceptor<Protocol, Service>& acceptor);
                      ^                               ~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:18:29: error: too many template arguments for class template 'basic_socket_acceptor'
void SocketServer::doListen(basic_socket_acceptor<Protocol, Service>& acceptor,
                            ^                               ~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:29:33: error: too many template arguments for class template 'basic_socket_acceptor'
void SocketServer::doAcceptOnce(basic_socket_acceptor<Protocol, Service>& acceptor) {
                                ^                               ~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:48:5: error: no matching member function for call to 'doListen'
    doListen(acceptor, tcp::endpoint(tcp::v4(), port));
    ^~~~~~~~
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:57:5: error: no matching member function for call to 'doAcceptOnce'
    doAcceptOnce(acceptor);
    ^~~~~~~~~~~~
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:70:5: error: no matching member function for call to 'doListen'
    doListen(acceptor, stream_protocol::endpoint(unixPath));
    ^~~~~~~~
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:78:5: error: no matching member function for call to 'doAcceptOnce'
    doAcceptOnce(acceptor);
    ^~~~~~~~~~~~
8 errors generated.
make[2]: *** [src/CMakeFiles/cucumber-cpp-nomain.dir/connectors/wire/WireServer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 81%] Building CXX object src/CMakeFiles/cucumber-cpp.dir/connectors/wire/WireProtocol.cpp.o
cd /tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/usr/local/include -I/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/include  -DBOOST_ALL_DYN_LINK -DNDEBUG   -o CMakeFiles/cucumber-cpp.dir/connectors/wire/WireProtocol.cpp.o -c /tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireProtocol.cpp
In file included from /tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:1:
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/include/cucumber-cpp/internal/connectors/wire/WireServer.hpp:39:19: error: too many template arguments for class template 'basic_socket_acceptor'
    void doListen(basic_socket_acceptor<Protocol, Service>& acceptor,
                  ^                               ~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
In file included from /tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:1:
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/include/cucumber-cpp/internal/connectors/wire/WireServer.hpp:42:23: error: too many template arguments for class template 'basic_socket_acceptor'
    void doAcceptOnce(basic_socket_acceptor<Protocol, Service>& acceptor);
                      ^                               ~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:18:29: error: too many template arguments for class template 'basic_socket_acceptor'
void SocketServer::doListen(basic_socket_acceptor<Protocol, Service>& acceptor,
                            ^                               ~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:29:33: error: too many template arguments for class template 'basic_socket_acceptor'
void SocketServer::doAcceptOnce(basic_socket_acceptor<Protocol, Service>& acceptor) {
                                ^                               ~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:48:5: error: no matching member function for call to 'doListen'
    doListen(acceptor, tcp::endpoint(tcp::v4(), port));
    ^~~~~~~~
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:57:5: error: no matching member function for call to 'doAcceptOnce'
    doAcceptOnce(acceptor);
    ^~~~~~~~~~~~
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:70:5: error: no matching member function for call to 'doListen'
    doListen(acceptor, stream_protocol::endpoint(unixPath));
    ^~~~~~~~
/tmp/cucumber-cpp-20171219-982-h5d53y/cucumber-cpp-0.4/src/connectors/wire/WireServer.cpp:78:5: error: no matching member function for call to 'doAcceptOnce'
    doAcceptOnce(acceptor);
    ^~~~~~~~~~~~
8 errors generated.
make[2]: *** [src/CMakeFiles/cucumber-cpp.dir/connectors/wire/WireServer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/cucumber-cpp-nomain.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/cucumber-cpp.dir/all] Error 2
make: *** [all] Error 2

==> Formula
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cucumber-cpp.rb
```

I've seen this commit https://github.com/cucumber/cucumber-cpp/commit/1b2187229e8a20547d444006cef37074a8c7ce50 but it looks like an unrelated issue.

**Comment by muggenhor** [comment]
FYI: this is the result of Boost.Asio changing in backwards incompatible ways

**Comment by konserw** [comment]
I believe it is fixed with #189. Please let us know if you are still having issues with building latest cucumber-cpp
