### PR TITLE
fix OSX build failing on warning

### PR DESCRIPTION
**Pull request by konserw**
## Summary

fix OSX build by removing -werror

## Motivation and Context

OSX builds started failing becouse of harmless warning treated as error

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] It is my own work, its copyright is implicitly assigned to the project and no substantial part of it has been copied from other sources (including [Stack Overflow](https://stackoverflow.com/)). In rare occasions this is acceptable, like in CMake modules where the original copyright information should be kept.
- [x] I'm using the same code standards as the existing code (indentation, spacing, variable naming, ...).
- [ ] I've added tests for my code.
- [x] I have verified whether my change requires changes to the documentation
- [x] My change either requires no documentation change or I've updated the documentation accordingly.
- [x] My branch has been rebased to master, keeping only relevant commits.

### CODE REVIEW

**Comment by matlo607** [comment]
What are those harmless warnings ?

**Comment by konserw** [comment]
https://travis-ci.org/cucumber/cucumber-cpp/jobs/341094255 -> 
```
In file included from ../examples/CalcQt/features/step_definitions/BoostCalculatorQtSteps.cpp:4:
../examples/CalcQt/features/step_definitions/CalculatorQtSteps.cpp:40:5: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
    QTest::qWaitForWindowExposed(&ctx->calculator);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
I just tried assigning to a variable which resulted in:
https://travis-ci.org/konserw/cucumber-cpp/jobs/341560068
```
../examples/CalcQt/features/step_definitions/CalculatorQtSteps.cpp:39:10: error: variable ‘_’ set but not used [-Werror=unused-but-set-variable]
     bool _; //just to suppress warning
          ^
cc1plus: all warnings being treated as errors
```
Honestly I don't think we should add artificial code just to suppress warnings. They are warnings and not errors after all.

**Comment by konserw** [comment]
I'll try with ` #pragma clang diagnostic ignored "-Wunused-result"`

**Comment by matlo607** [comment]
I proposed 1b5ed236d9c68ea483c81268cbf1c32a5b6d1e93 in my pull requests.
The result of `QTest::qWaitForWindowShown` / `QTest::qWaitForWindowExposed` should be actually used.

**Comment by matlo607** [comment]
By the way, do you know who is in charge of reviewing pull requests on this project ?
A lot of pull requests are green and have not been accepted nor rejected.

**Comment by konserw** [comment]
but your use of it doesn't make any sense - that waiting function is there for user to actually see what is happening (how cucumber is "clicking") if user wants to;  and by default does nothing (waits for 0 ms)

As for reviewers: @paoloambrosio @muggenhor and I supose me...

**Comment by matlo607** [comment]
I trust you if you say so. Actually I am not a cucumber user, I just had to build it and provide an artifact for a team and fixed the build with boost-1.66.0
I will remove commit 1b5ed23 from my pull request once you will have fixed this issue.
Thanks for your feedback.

**Comment by konserw** [comment]
Ok so the question now is if we need to keep -werror and apply this PR or could we just disable -werror ?
@muggenhor @paoloambrosio what do you think ?

**Comment by konserw** [comment]
I went with disabling -werror on my devel branch. If merging is unblocked I would push it also here.

**Comment by matlo607** [comment]
Any news about the reviewers ?
This pull request has been opened for more than 1 month ago.

**Comment by konserw** [comment]
@matlo607 could you please create pull request with just removing -werror ? I'll review and merge it afterwords

**Comment by konserw** [comment]
Merged as part of #189
