### ISSUE TITLE
Boost 1.7x build incompatibility due to invalid method signature

### ISSUE THREAD

**Issue by dmeehan1968** [cucumber/cucumber-cpp#238]
Failing Code:
- https://github.com/cucumber/cucumber-cpp/blob/dd424c1a900cb41c5db9d481714eb3471ce195e3/src/drivers/BoostDriver.cpp#L53

Boost commit that breaks Cucumber-cpp:
-  https://github.com/boostorg/test/commit/7e20f966dca4e4b49585bbe7654334f31b35b3db

Compiler Error:
```
.../cucumber-cpp/src/drivers/BoostDriver.cpp:53:10: error: 'cucumber::internal::CukeBoostLogInterceptor::log_build_info' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void log_build_info( std::ostream&) {};
         ^
/usr/local/include/boost/test/unit_test_log_formatter.hpp:144:25: note: hidden overloaded virtual function 'boost::unit_test::unit_test_log_formatter::log_build_info' declared here: different number of parameters (2 vs 1)
    virtual void        log_build_info( std::ostream& os, bool log_build_info = true ) = 0;
                        ^
.../cucumber-cpp/src/drivers/BoostDriver.cpp:122:26: error: allocating an object of abstract class type 'cucumber::internal::CukeBoostLogInterceptor'
    logInterceptor = new CukeBoostLogInterceptor;
                         ^
/usr/local/include/boost/test/unit_test_log_formatter.hpp:144:25: note: unimplemented pure virtual method 'log_build_info' in 'CukeBoostLogInterceptor'
    virtual void        log_build_info( std::ostream& os, bool log_build_info = true ) = 0;
                        ^
2 errors generated.
```

**Comment by dmeehan1968** [comment]
Pull Request: https://github.com/cucumber/cucumber-cpp/pull/239

**Comment by jermus67** [comment]
Pull Request: #239 was marked (by @dmeehan1968) as a duplicate of pull request #225 . Pull request #225 has been merged, and the main branch now compiles with boost 1.7x.

Based on the above described observation I think this issue can be closed.

Thanks for the energy you put in helping fix the issue.
